// GENERATED by scripts/generate-pictures.mjs — do not edit.
// Source: assets/coloring/*.svg  ·  regenerate: npm run gen:pictures

import type { Picture } from "./pictures.types";

export const PICTURES: Picture[] = [
  {
    "id": "bird",
    "title": "Bird",
    "emoji": "🐦",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "tail",
        "kind": "path",
        "d": "M48 130 C 16 112 2 136 4 166 C 8 190 32 196 56 180 C 48 164 44 144 48 130 Z"
      },
      {
        "id": "body",
        "kind": "ellipse",
        "cx": 104,
        "cy": 148,
        "rx": 78,
        "ry": 72
      },
      {
        "id": "wing",
        "kind": "path",
        "d": "M112 122 C 86 152 90 196 124 214 C 154 202 166 166 152 138 C 138 118 120 112 112 122 Z"
      },
      {
        "id": "head",
        "kind": "circle",
        "cx": 182,
        "cy": 90,
        "r": 40
      },
      {
        "id": "beak",
        "kind": "path",
        "d": "M216 82 L 240 90 L 216 98 Z"
      },
      {
        "id": "eye",
        "kind": "circle",
        "cx": 194,
        "cy": 78,
        "r": 6
      }
    ],
    "decorations": [
      {
        "d": "M92 216 L 92 234"
      },
      {
        "d": "M122 216 L 122 234"
      }
    ]
  },
  {
    "id": "butterfly",
    "title": "Butterfly",
    "emoji": "🦋",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "wing-top-left",
        "kind": "path",
        "d": "M120 78 C 96 32 44 24 26 52 C 18 80 34 106 70 114 C 100 120 120 104 120 78 Z"
      },
      {
        "id": "wing-top-right",
        "kind": "path",
        "d": "M120 78 C 144 32 196 24 214 52 C 222 80 206 106 170 114 C 140 120 120 104 120 78 Z"
      },
      {
        "id": "wing-bottom-left",
        "kind": "path",
        "d": "M120 120 C 100 128 58 130 46 160 C 38 186 66 212 94 200 C 116 190 122 150 120 120 Z"
      },
      {
        "id": "wing-bottom-right",
        "kind": "path",
        "d": "M120 120 C 140 128 182 130 194 160 C 202 186 174 212 146 200 C 124 190 118 150 120 120 Z"
      },
      {
        "id": "spot-left",
        "kind": "circle",
        "cx": 62,
        "cy": 70,
        "r": 12
      },
      {
        "id": "spot-right",
        "kind": "circle",
        "cx": 178,
        "cy": 70,
        "r": 12
      },
      {
        "id": "body",
        "kind": "ellipse",
        "cx": 120,
        "cy": 122,
        "rx": 10,
        "ry": 60
      },
      {
        "id": "head",
        "kind": "circle",
        "cx": 120,
        "cy": 58,
        "r": 11
      }
    ],
    "decorations": [
      {
        "d": "M120 64 C 108 42 92 32 78 28"
      },
      {
        "d": "M120 64 C 132 42 148 32 162 28"
      }
    ]
  },
  {
    "id": "cat",
    "title": "Cat",
    "emoji": "🐱",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "tail",
        "kind": "path",
        "d": "M170 220 C 210 210 224 170 210 130 C 226 168 220 214 176 232 Z"
      },
      {
        "id": "body",
        "kind": "path",
        "d": "M70 236 C 60 180 70 140 120 140 C 170 140 180 180 170 236 Z"
      },
      {
        "id": "ear-left",
        "kind": "path",
        "d": "M78 66 C 70 46 62 30 66 20 C 82 30 100 44 108 54 C 96 60 86 64 78 66 Z"
      },
      {
        "id": "ear-right",
        "kind": "path",
        "d": "M162 66 C 170 46 178 30 174 20 C 158 30 140 44 132 54 C 144 60 154 64 162 66 Z"
      },
      {
        "id": "head",
        "kind": "circle",
        "cx": 120,
        "cy": 100,
        "r": 50
      },
      {
        "id": "eye-left",
        "kind": "circle",
        "cx": 100,
        "cy": 96,
        "r": 7
      },
      {
        "id": "eye-right",
        "kind": "circle",
        "cx": 140,
        "cy": 96,
        "r": 7
      },
      {
        "id": "nose",
        "kind": "circle",
        "cx": 120,
        "cy": 118,
        "r": 6
      }
    ],
    "decorations": [
      {
        "d": "M110 130 Q 120 138 130 130"
      }
    ]
  },
  {
    "id": "dinosaur",
    "title": "Dinosaur",
    "emoji": "🦕",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "tail",
        "kind": "path",
        "d": "M64 140 C 30 130 10 140 4 156 C 10 170 34 172 62 164 Z"
      },
      {
        "id": "body",
        "kind": "ellipse",
        "cx": 120,
        "cy": 150,
        "rx": 60,
        "ry": 40
      },
      {
        "id": "neck",
        "kind": "path",
        "d": "M156 130 C 176 100 190 74 192 52 C 172 52 156 70 148 96 C 146 110 150 122 156 130 Z"
      },
      {
        "id": "head",
        "kind": "ellipse",
        "cx": 198,
        "cy": 44,
        "rx": 26,
        "ry": 22
      },
      {
        "id": "leg-front",
        "kind": "rect",
        "x": 150,
        "y": 176,
        "width": 20,
        "height": 40,
        "rx": 6
      },
      {
        "id": "leg-back",
        "kind": "rect",
        "x": 90,
        "y": 176,
        "width": 20,
        "height": 40,
        "rx": 6
      },
      {
        "id": "eye",
        "kind": "circle",
        "cx": 206,
        "cy": 38,
        "r": 5
      }
    ],
    "decorations": [
      {
        "d": "M188 50 q 8 6 4 14"
      }
    ]
  },
  {
    "id": "duck",
    "title": "Duck",
    "emoji": "🦆",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "tail",
        "kind": "path",
        "d": "M28 132 C 12 118 8 98 20 84 C 32 98 36 118 38 136 Z"
      },
      {
        "id": "body",
        "kind": "ellipse",
        "cx": 108,
        "cy": 162,
        "rx": 90,
        "ry": 64
      },
      {
        "id": "wing",
        "kind": "path",
        "d": "M68 142 C 48 170 54 204 88 216 C 114 208 124 178 110 152 C 96 134 78 132 68 142 Z"
      },
      {
        "id": "head",
        "kind": "circle",
        "cx": 168,
        "cy": 96,
        "r": 46
      },
      {
        "id": "bill",
        "kind": "path",
        "d": "M206 92 C 226 88 240 94 240 104 C 240 114 224 118 204 112 Z"
      },
      {
        "id": "eye",
        "kind": "circle",
        "cx": 180,
        "cy": 82,
        "r": 6
      }
    ],
    "decorations": [
      {
        "d": "M30 230 q 24 10 48 0"
      },
      {
        "d": "M120 232 q 24 10 48 0"
      }
    ]
  },
  {
    "id": "fish",
    "title": "Fish",
    "emoji": "🐠",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "tail",
        "kind": "path",
        "d": "M168 120 C 194 94 214 80 228 76 C 222 100 222 140 228 164 C 214 160 194 146 168 120 Z"
      },
      {
        "id": "fin-top",
        "kind": "path",
        "d": "M92 80 C 108 48 136 42 152 46 C 142 62 120 76 100 84 Z"
      },
      {
        "id": "fin-bottom",
        "kind": "path",
        "d": "M92 160 C 108 192 136 198 152 194 C 142 178 120 164 100 156 Z"
      },
      {
        "id": "body",
        "kind": "ellipse",
        "cx": 104,
        "cy": 120,
        "rx": 70,
        "ry": 52
      },
      {
        "id": "eye",
        "kind": "circle",
        "cx": 70,
        "cy": 104,
        "r": 11
      },
      {
        "id": "bubble-1",
        "kind": "circle",
        "cx": 44,
        "cy": 64,
        "r": 10
      },
      {
        "id": "bubble-2",
        "kind": "circle",
        "cx": 22,
        "cy": 38,
        "r": 7
      },
      {
        "id": "bubble-3",
        "kind": "circle",
        "cx": 50,
        "cy": 30,
        "r": 6
      }
    ],
    "decorations": [
      {
        "d": "M58 122 q 16 15 34 2"
      },
      {
        "d": "M96 96 q 14 14 0 28"
      },
      {
        "d": "M122 92 q 14 16 0 34"
      }
    ]
  },
  {
    "id": "flower",
    "title": "Flower",
    "emoji": "🌸",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "stem",
        "kind": "path",
        "d": "M114 150 C 110 180 112 205 120 228 C 128 205 130 180 126 150 Z"
      },
      {
        "id": "leaf-left",
        "kind": "path",
        "d": "M116 176 C 84 164 54 168 38 190 C 64 202 100 200 118 186 Z"
      },
      {
        "id": "leaf-right",
        "kind": "path",
        "d": "M124 200 C 152 190 182 194 198 212 C 176 224 140 222 122 210 Z"
      },
      {
        "id": "petal-1",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "petal-2",
        "transform": "rotate(72 120 95)",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "petal-3",
        "transform": "rotate(144 120 95)",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "petal-4",
        "transform": "rotate(216 120 95)",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "petal-5",
        "transform": "rotate(288 120 95)",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "center",
        "kind": "circle",
        "cx": 120,
        "cy": 95,
        "r": 26
      }
    ],
    "decorations": []
  },
  {
    "id": "house",
    "title": "House",
    "emoji": "🏠",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "grass",
        "kind": "path",
        "d": "M0 198 C 60 188 180 188 240 198 L 240 240 L 0 240 Z"
      },
      {
        "id": "sun",
        "kind": "circle",
        "cx": 206,
        "cy": 40,
        "r": 22
      },
      {
        "id": "cloud",
        "kind": "path",
        "d": "M26 62 q -16 0 -16 -16 q 0 -16 16 -15 q 5 -15 22 -12 q 13 -9 26 4 q 17 -2 17 15 q 0 16 -17 16 Z"
      },
      {
        "id": "chimney",
        "kind": "path",
        "d": "M150 74 L 150 40 L 178 40 L 178 92 Z"
      },
      {
        "id": "roof",
        "kind": "path",
        "d": "M36 106 L 120 38 L 204 106 Z"
      },
      {
        "id": "wall",
        "kind": "rect",
        "x": 58,
        "y": 106,
        "width": 124,
        "height": 94
      },
      {
        "id": "door",
        "kind": "rect",
        "x": 104,
        "y": 142,
        "width": 32,
        "height": 58,
        "rx": 4
      },
      {
        "id": "window-left",
        "kind": "rect",
        "x": 72,
        "y": 122,
        "width": 26,
        "height": 26,
        "rx": 3
      },
      {
        "id": "window-right",
        "kind": "rect",
        "x": 142,
        "y": 122,
        "width": 26,
        "height": 26,
        "rx": 3
      }
    ],
    "decorations": []
  },
  {
    "id": "rocket",
    "title": "Rocket",
    "emoji": "🚀",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "star-1",
        "kind": "circle",
        "cx": 40,
        "cy": 48,
        "r": 7
      },
      {
        "id": "star-2",
        "kind": "circle",
        "cx": 202,
        "cy": 62,
        "r": 7
      },
      {
        "id": "star-3",
        "kind": "circle",
        "cx": 34,
        "cy": 150,
        "r": 6
      },
      {
        "id": "flame",
        "kind": "path",
        "d": "M94 168 C 84 196 92 224 120 240 C 148 224 156 196 146 168 Z"
      },
      {
        "id": "fin-left",
        "kind": "path",
        "d": "M88 140 C 62 152 46 182 50 202 C 72 196 88 176 94 156 Z"
      },
      {
        "id": "fin-right",
        "kind": "path",
        "d": "M152 140 C 178 152 194 182 190 202 C 168 196 152 176 146 156 Z"
      },
      {
        "id": "body",
        "kind": "path",
        "d": "M120 18 C 150 44 158 96 152 142 C 152 162 88 162 88 142 C 82 96 90 44 120 18 Z"
      },
      {
        "id": "window",
        "kind": "circle",
        "cx": 120,
        "cy": 86,
        "r": 18
      },
      {
        "id": "nozzle",
        "kind": "path",
        "d": "M96 150 L 144 150 L 136 168 L 104 168 Z"
      }
    ],
    "decorations": []
  },
  {
    "id": "whale",
    "title": "Whale",
    "emoji": "🐋",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "fin",
        "kind": "path",
        "d": "M62 176 C 46 202 28 212 14 208 C 24 186 40 172 58 164 Z"
      },
      {
        "id": "tail-fluke",
        "kind": "path",
        "d": "M158 120 C 176 80 196 40 214 18 C 210 46 202 70 214 92 C 224 70 230 46 236 24 C 232 62 224 100 196 128 C 182 138 168 132 158 120 Z"
      },
      {
        "id": "body",
        "kind": "ellipse",
        "cx": 96,
        "cy": 146,
        "rx": 84,
        "ry": 58
      },
      {
        "id": "belly",
        "kind": "path",
        "d": "M14 156 C 46 186 148 186 178 156 C 148 174 46 174 14 156 Z"
      },
      {
        "id": "blowhole",
        "kind": "ellipse",
        "cx": 60,
        "cy": 92,
        "rx": 6,
        "ry": 3
      },
      {
        "id": "eye",
        "kind": "circle",
        "cx": 46,
        "cy": 128,
        "r": 7
      }
    ],
    "decorations": [
      {
        "d": "M56 68 q 4 -16 -2 -30"
      },
      {
        "d": "M68 68 q 8 -20 -2 -36"
      }
    ]
  }
];
