// GENERATED by scripts/generate-pictures.mjs — do not edit.
// Source: assets/coloring/*.svg  ·  regenerate: npm run gen:pictures

import type { Picture } from "./pictures.types";

export const PICTURES: Picture[] = [
  {
    "id": "butterfly",
    "title": "Butterfly",
    "emoji": "🦋",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "wing-top-left",
        "kind": "path",
        "d": "M120 78 C 96 32 44 24 26 52 C 18 80 34 106 70 114 C 100 120 120 104 120 78 Z"
      },
      {
        "id": "wing-top-right",
        "kind": "path",
        "d": "M120 78 C 144 32 196 24 214 52 C 222 80 206 106 170 114 C 140 120 120 104 120 78 Z"
      },
      {
        "id": "wing-bottom-left",
        "kind": "path",
        "d": "M120 120 C 100 128 58 130 46 160 C 38 186 66 212 94 200 C 116 190 122 150 120 120 Z"
      },
      {
        "id": "wing-bottom-right",
        "kind": "path",
        "d": "M120 120 C 140 128 182 130 194 160 C 202 186 174 212 146 200 C 124 190 118 150 120 120 Z"
      },
      {
        "id": "spot-left",
        "kind": "circle",
        "cx": 62,
        "cy": 70,
        "r": 12
      },
      {
        "id": "spot-right",
        "kind": "circle",
        "cx": 178,
        "cy": 70,
        "r": 12
      },
      {
        "id": "body",
        "kind": "ellipse",
        "cx": 120,
        "cy": 122,
        "rx": 10,
        "ry": 60
      },
      {
        "id": "head",
        "kind": "circle",
        "cx": 120,
        "cy": 58,
        "r": 11
      }
    ],
    "decorations": [
      {
        "d": "M120 64 C 108 42 92 32 78 28"
      },
      {
        "d": "M120 64 C 132 42 148 32 162 28"
      }
    ]
  },
  {
    "id": "fish",
    "title": "Fish",
    "emoji": "🐠",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "tail",
        "kind": "path",
        "d": "M168 120 C 194 94 214 80 228 76 C 222 100 222 140 228 164 C 214 160 194 146 168 120 Z"
      },
      {
        "id": "fin-top",
        "kind": "path",
        "d": "M92 80 C 108 48 136 42 152 46 C 142 62 120 76 100 84 Z"
      },
      {
        "id": "fin-bottom",
        "kind": "path",
        "d": "M92 160 C 108 192 136 198 152 194 C 142 178 120 164 100 156 Z"
      },
      {
        "id": "body",
        "kind": "ellipse",
        "cx": 104,
        "cy": 120,
        "rx": 70,
        "ry": 52
      },
      {
        "id": "eye",
        "kind": "circle",
        "cx": 70,
        "cy": 104,
        "r": 11
      },
      {
        "id": "bubble-1",
        "kind": "circle",
        "cx": 44,
        "cy": 64,
        "r": 10
      },
      {
        "id": "bubble-2",
        "kind": "circle",
        "cx": 22,
        "cy": 38,
        "r": 7
      },
      {
        "id": "bubble-3",
        "kind": "circle",
        "cx": 50,
        "cy": 30,
        "r": 6
      }
    ],
    "decorations": [
      {
        "d": "M58 122 q 16 15 34 2"
      },
      {
        "d": "M96 96 q 14 14 0 28"
      },
      {
        "d": "M122 92 q 14 16 0 34"
      }
    ]
  },
  {
    "id": "flower",
    "title": "Flower",
    "emoji": "🌸",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "stem",
        "kind": "path",
        "d": "M114 150 C 110 180 112 205 120 228 C 128 205 130 180 126 150 Z"
      },
      {
        "id": "leaf-left",
        "kind": "path",
        "d": "M116 176 C 84 164 54 168 38 190 C 64 202 100 200 118 186 Z"
      },
      {
        "id": "leaf-right",
        "kind": "path",
        "d": "M124 200 C 152 190 182 194 198 212 C 176 224 140 222 122 210 Z"
      },
      {
        "id": "petal-1",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "petal-2",
        "transform": "rotate(72 120 95)",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "petal-3",
        "transform": "rotate(144 120 95)",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "petal-4",
        "transform": "rotate(216 120 95)",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "petal-5",
        "transform": "rotate(288 120 95)",
        "kind": "path",
        "d": "M120 95 C 95 60 95 22 120 14 C 145 22 145 60 120 95 Z"
      },
      {
        "id": "center",
        "kind": "circle",
        "cx": 120,
        "cy": 95,
        "r": 26
      }
    ],
    "decorations": []
  },
  {
    "id": "house",
    "title": "House",
    "emoji": "🏠",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "grass",
        "kind": "path",
        "d": "M0 198 C 60 188 180 188 240 198 L 240 240 L 0 240 Z"
      },
      {
        "id": "sun",
        "kind": "circle",
        "cx": 206,
        "cy": 40,
        "r": 22
      },
      {
        "id": "cloud",
        "kind": "path",
        "d": "M26 62 q -16 0 -16 -16 q 0 -16 16 -15 q 5 -15 22 -12 q 13 -9 26 4 q 17 -2 17 15 q 0 16 -17 16 Z"
      },
      {
        "id": "chimney",
        "kind": "path",
        "d": "M150 74 L 150 40 L 178 40 L 178 92 Z"
      },
      {
        "id": "roof",
        "kind": "path",
        "d": "M36 106 L 120 38 L 204 106 Z"
      },
      {
        "id": "wall",
        "kind": "rect",
        "x": 58,
        "y": 106,
        "width": 124,
        "height": 94
      },
      {
        "id": "door",
        "kind": "rect",
        "x": 104,
        "y": 142,
        "width": 32,
        "height": 58,
        "rx": 4
      },
      {
        "id": "window-left",
        "kind": "rect",
        "x": 72,
        "y": 122,
        "width": 26,
        "height": 26,
        "rx": 3
      },
      {
        "id": "window-right",
        "kind": "rect",
        "x": 142,
        "y": 122,
        "width": 26,
        "height": 26,
        "rx": 3
      }
    ],
    "decorations": []
  },
  {
    "id": "rocket",
    "title": "Rocket",
    "emoji": "🚀",
    "viewBox": "0 0 240 240",
    "regions": [
      {
        "id": "star-1",
        "kind": "circle",
        "cx": 40,
        "cy": 48,
        "r": 7
      },
      {
        "id": "star-2",
        "kind": "circle",
        "cx": 202,
        "cy": 62,
        "r": 7
      },
      {
        "id": "star-3",
        "kind": "circle",
        "cx": 34,
        "cy": 150,
        "r": 6
      },
      {
        "id": "flame",
        "kind": "path",
        "d": "M94 168 C 84 196 92 224 120 240 C 148 224 156 196 146 168 Z"
      },
      {
        "id": "fin-left",
        "kind": "path",
        "d": "M88 140 C 62 152 46 182 50 202 C 72 196 88 176 94 156 Z"
      },
      {
        "id": "fin-right",
        "kind": "path",
        "d": "M152 140 C 178 152 194 182 190 202 C 168 196 152 176 146 156 Z"
      },
      {
        "id": "body",
        "kind": "path",
        "d": "M120 18 C 150 44 158 96 152 142 C 152 162 88 162 88 142 C 82 96 90 44 120 18 Z"
      },
      {
        "id": "window",
        "kind": "circle",
        "cx": 120,
        "cy": 86,
        "r": 18
      },
      {
        "id": "nozzle",
        "kind": "path",
        "d": "M96 150 L 144 150 L 136 168 L 104 168 Z"
      }
    ],
    "decorations": []
  }
];
