/**
 * Tiny sound-effect layer over expo-audio.
 *
 * Effects live in assets/sounds/*.wav — generated by `npm run gen:sounds`
 * (scripts/generate-sounds.mjs). One persistent player per effect, created
 * once at app start; `playSound` restarts it from 0 so rapid taps re-trigger.
 */
import {
  createAudioPlayer,
  setAudioModeAsync,
  type AudioPlayer,
} from "expo-audio";

const SOURCES = {
  pop: require("../../assets/sounds/pop.wav"),
  tap: require("../../assets/sounds/tap.wav"),
  win: require("../../assets/sounds/win.wav"),
} as const;

export type SoundName = keyof typeof SOURCES;

let players: Record<SoundName, AudioPlayer> | null = null;
let enabled = true;

/** call once from the root layout */
export function initSounds() {
  setAudioModeAsync({ playsInSilentMode: true }).catch(() => {});
  if (players) return;
  const entries = Object.entries(SOURCES).map(([name, src]) => [
    name,
    createAudioPlayer(src),
  ]);
  players = Object.fromEntries(entries) as Record<SoundName, AudioPlayer>;
}

export function playSound(name: SoundName) {
  if (!enabled || !players) return;
  const player = players[name];
  try {
    player.seekTo(0);
    player.play();
  } catch {
    // player not ready yet — ignore
  }
}

export function setSoundEnabled(value: boolean) {
  enabled = value;
}

export function isSoundEnabled() {
  return enabled;
}
